version: 0.2
env:
  exported-variables:
    - APP_VERSION_CB
phases:
  install:
    runtime-versions:
      dotnet: 8.0
  build:
    commands:
      - echo "Leyendo la version de la aplicacion..."
      - APP_VERSION=$(cat VERSION.txt)
      - echo "Version de la aplicacion $APP_VERSION"
      - export APP_VERSION_CB="$APP_VERSION"
      - echo "Restaurando dependencias..."
      - dotnet restore
      - echo "Publicando la aplicación en modo Release..."
      - "dotnet publish -c Release -o output /p:Version=\"$APP_VERSION\""
  post_build:
    commands:
      - echo "Creando el paquete de despliegue (version $APP_VERSION_CB)..."
      - cd output
      - "zip -r ../application-$APP_VERSION_CB.zip *"
      - cd ..
artifacts:
  files:
    - application-$APP_VERSION_CB.zip
  name: application-$APP_VERSION_CB