version: 0.2
phases:
  build:
    commands:
      - echo "Leyendo la versión de la aplicación..."
      - APP_VERSION=$(cat VERSION.txt)
      - echo "Versión de la aplicación: $APP_VERSION"
      - echo "Restaurando dependencias..."
      - dotnet restore
      - echo "Publicando la aplicación en modo Release..."
      - "dotnet publish -c Release -o output /p:Version=\"$APP_VERSION\"" 
    commands:
      - echo "Creando el paquete de despliegue (versión $APP_VERSION)..."
      - cd output
      - "zip -r ../application-$APP_VERSION.zip *"
      - cd ..
artifacts:
  files:
    - application-$APP_VERSION.zip
  name: application-$APP_VERSION