version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 6.0
  build:
    commands:
      - echo "Restaurando dependencias..."
      - dotnet restore
      - echo "Publicando la aplicación en modo Release..."
      - dotnet publish -c Release -o output
  post_build:
    commands:
      - echo "Creando el paquete de despliegue..."
      - cd output
      - zip -r ../application.zip *
      - cd ..
artifacts:
  files:
    - application.zip
