version: 0.2
env:
  exported-variables:
    - APP_VERSION_CB
phases:
  install:
    runtime-versions:
      dotnet: 8.0
  build:
    commands:
      - echo "Leyendo la version de la aplicacion..."
      - APP_VERSION=$(cat VERSION.txt)
      - echo "Version de la aplicacion $APP_VERSION"
      - export APP_VERSION_CB="$APP_VERSION"
      - echo "Restaurando dependencias..."
      - dotnet restore
      - echo "Publicando la aplicación en modo Release..."
      - "dotnet publish -c Release -o ./publish"
artifacts:
  files:
    - '**/*'
  base-directory: publish
  name: application.zip